djangoPreject/djangoPreject/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('system/', include(('system.urls', 'system'), namespace='system')),
]

djangoPreject/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.Register, name='register'),
    path('delete/<int:id>', views.Delete, name='delete'),
]

djangoPreject/user/models.py
from django.db import models

# Create your models here.

djangoPreject/user/forms.py
from django import forms
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password(self):
        data = self.cleaned_data
        if data.get('password1') == data.get('password2'):
            return data.get('password1')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

djangoPreject/user/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserLoginForm, UserRegisterForm

@login_required(login_url='/login/')
def index(request):
    return render(request, 'user/login.html')

def Login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect('system:index')
            else:
                return HttpResponse("账号或密码输入有误。请重新输入～")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == "GET":
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'user/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

def Register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password1'])
            new_user.save()
            return redirect("user:login")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'user/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

def Logout(request):
    logout(request)
    return render(request, 'user/login.html')

@login_required(login_url='/login/')
def Delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('user:login')
        else:
            return HttpResponse('你没有删除操作的权限。')
    else:
        return HttpResponse("仅接受post请求。")

djangoPreject/templates/user/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
    <style>
        .form-control{
            width: 30%;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <h5>还没有账号？</h5>
                <h5>点击<a href="{% url 'user:register' %}" style="color: lightskyblue;">注册账号</a>加入我们吧！</h5>
                <br>
                <form method="post" action="{% url 'user:login' %}">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
                <br>
            </div>
        </div>
    </div>
{% endblock content %}

djangoPreject/templates/user/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 注册 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="{% url 'user:register' %}">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password1">设置密码</label>
                    <input type="password" class="form-control" id="password1" name="password1" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <div class="form-group col-md-4">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}