djangoPreject/djangoPreject/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('system/', include(('system.urls', 'system'), namespace='system')),
]

djangoPreject/system/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('word_cloud/', views.word_cloud, name='word_cloud'),
    path('average_sentiment/', views.average_sentiment, name='average_sentiment'),
    path('pie_chart/', views.pie_chart, name='pie_chart'),
    path('comment_list/', views.comment_list, name='comment_list'),
    path('index/', views.index, name='index'),
    path('show/', views.show, name='show'),
    path('chart1/', views.chart1, name='chart1'),
    path('chart2/', views.chart2, name='chart2'),
    path('recommend/', views.recommend, name='recommend'),
    path('get_echart_data/', views.get_echart_data, name='get_echart_data')
]

djangoPreject/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.Register, name='register'),
    path('delete/<int:id>', views.Delete, name='delete'),
]

djangoPreject/system/models.py
from django.db import models

class Comment(models.Model):
    uid = models.CharField(verbose_name="uid",max_length=100)
    nickname = models.CharField(verbose_name="昵称",max_length=100)
    content = models.CharField(verbose_name="评论内容",max_length=100)
    date = models.DateField(verbose_name="日期")
    polarity = models.CharField(verbose_name="评论情感极性",max_length=10)
    probability = models.FloatField(verbose_name="评论情感概率")

class Book(models.Model):
    category = models.CharField(verbose_name="类别",max_length=255,null=True)
    title = models.CharField(verbose_name="标题",max_length=255,null=True)
    author = models.CharField(verbose_name="作者",max_length=255,null=True)
    createTime = models.CharField(verbose_name="发布时间",max_length=255,null=True)
    press = models.CharField(verbose_name="出版社",max_length=255,null=True)
    now_price = models.FloatField(verbose_name="现价", default=0)
    pre_price = models.FloatField(verbose_name="原价", default=0)
    discount = models.FloatField(verbose_name="折扣", default=0)
    detail = models.TextField(verbose_name='详情',null=True)
    star = models.IntegerField(verbose_name="评分", default=0)
    comment_num = models.IntegerField(verbose_name="评论数量", default=0)
    img_url = models.CharField(verbose_name='图片链接',max_length=255,null=True)
    book_url = models.CharField(verbose_name='舆情链接',max_length=255,null=True)
    addTime = models.CharField(verbose_name='采集时间',max_length=255,null=True)

    class Meta:
        verbose_name = "舆情信息"
        verbose_name_plural = "舆情信息"
        db_table = "booktable"

    def short_detail(self):
        if len(str(self.detail)) > 10:
            return '{}...'.format(str(self.detail)[0:9])
        else:
            return str(self.detail)

    short_detail.allow_tags = True
    short_detail.short_description = '详情'



    def short_title(self):
        if len(str(self.title)) > 10:
            return '{}...'.format(str(self.title)[0:9])
        else:
            return str(self.title)

    short_title.allow_tags = True
    short_title.short_description = '标题'

djangoPreject/system/views.py
import time
from collections import Counter
import jieba
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Book
import numpy as np
from django.db.models import Count

from django.shortcuts import render
from pyecharts.charts import Line
from .models import Comment  # 假设你有一个Comment模型，用于存储评论数据
from django.shortcuts import render
from django.http import JsonResponse
import json

from django.shortcuts import render
from pyecharts import options as opts
from pyecharts.charts import WordCloud
from pyecharts.globals import SymbolType

def word_cloud(request):
    filepath='/Users/k/project/Book_Analysis/O2FmEjpUU_word.txt'
    word_count = {}
    fp = open(filepath,'r',encoding='utf8')
    for line in fp:
        new_line=[]
        if len(line)>1:
            line = line.strip().split(' ')
            for word in line:
                if word in word_count:
                    word_count[word] += 1
                else:
                    word_count[word] = 1

    del word_count['spanclass']
    del word_count['url']
    del word_count['icon']
    words = [(word, count) for word, count in word_count.items()]
    # 构造词云图数据
    # words = [
    #     ("Python", 10000),
    #     ("Django", 6181),
    #     ("Flask", 4386),
    #     ("Java", 4055),
    #     ("C++", 2467),
    #     ("JavaScript", 2244),
    #     # 其他词语...
    # ]

    # 绘制词云图
    c = (
        WordCloud()
        .add("", words, word_size_range=[20, 100], shape=SymbolType.DIAMOND)
        .set_global_opts(title_opts=opts.TitleOpts(title="词云图示例"))
    )

    # 将图表转换为 HTML 字符串
    word_cloud_html = c.render_embed()

    return render(request, 'system/word_cloud.html', {'word_cloud_html': word_cloud_html})


def average_sentiment(request):
    # 获取评论数据
    comments = Comment.objects.all()

    # 计算每天评论情感概率的平均值
    date_sentiment_avg = {}
    for comment in comments:
        date = comment.date
        sentiment = comment.probability
        if date in date_sentiment_avg:
            date_sentiment_avg[date].append(sentiment)
        else:
            date_sentiment_avg[date] = [sentiment]

    date_avg = []
    sentiment_avg = []
    for date, sentiment_list in date_sentiment_avg.items():
        avg = sum(sentiment_list) / len(sentiment_list)
        date_avg.append(date.strftime('%Y-%m-%d'))
        sentiment_avg.append(avg)

    # 将数据转换为 JSON 格式
    data = {'dates': date_avg, 'sentiments': sentiment_avg}
    return render(request, 'system/sentiment_avg_line_chart.html', {'data': json.dumps(data)})

    return render(request, 'system/sentiment_avg_line_chart.html')


from django.shortcuts import render
from pyecharts import options as opts
from pyecharts.charts import Pie
from collections import Counter

def pie_chart(request):
    # 统计 polarity 字段中不同值的数量
    comments = Comment.objects.all()
    polarity_counts = Counter(comment.polarity for comment in comments)

    # 获取极性值和数量
    polarities = list(polarity_counts.keys())
    counts = list(polarity_counts.values())
    # 创建一个饼图
    c = (
        Pie()
        .add("", [list(z) for z in zip(polarities, counts)])
        .set_global_opts(title_opts=opts.TitleOpts(title="评论情感倾向分布饼图"))
    )
    # 将饼图转换为HTML格式的字符串
    pie_html = c.render_embed()
    return render(request, 'system/chart_pie.html', {'pie_html': pie_html})


from django.shortcuts import render
from .models import Comment

def comment_list(request):
    comments = Comment.objects.all()
    return render(request, 'system/comment_list.html', {'comments': comments})


@login_required(login_url='/login/')
def index(request):
    return render(request, 'system/index.html')

@login_required(login_url='/login/')
def show(request):
    books = Book.objects.all()
    date = time.strftime("%Y-%m-%d", time.localtime())
    count_today = len(books.filter(addTime__gt=date))
    count_sum = len(books)
    return render(request, 'system/show.html',context={'count_today':count_today,'count_sum':count_sum})

@login_required(login_url='/login/')
def chart1(request):
    category = request.GET.get('category')
    categories = Book.objects.order_by('category').values('category').distinct()
    data = {}
    if category:
        prices = list(Book.objects.all().filter(category=category).values_list('now_price', flat=True))
        bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, np.inf]
        bin_names = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90', '90-100', '100+']
        # 将价格分组
        counts, bins = np.histogram(prices, bins=bins)
        # 构造返回结果
        # x_data = [str(bins[i]) + '-' + str(bins[i + 1]) for i in range(len(bins) - 1)]
        y_data = counts.tolist()

        data['x_data'] = bin_names
        data['y_data'] = y_data

    return render(request, 'system/chart1.html', context={'categories':categories,'data':data,'category':category})

@login_required(login_url='/login/')
def chart2(request):
    category = request.GET.get('category')
    categories = Book.objects.order_by('category').values('category').distinct()
    data = {}
    if category:
        publishers = Book.objects.all().filter(category=category).values('press').annotate(count=Count('id')).order_by('-count')
        data['x_data'] = []
        data['y_data'] = []
        for item in publishers[:5]:
            data['x_data'].append(item['press'])
            data['y_data'].append({'name':item['press'],'value':item['count']})
    return render(request, 'system/chart2.html', context={'categories':categories,'category':category,'data':data})


@login_required(login_url='/login/')
def recommend(request):
    books = Book.objects.all().order_by('-comment_num')
    paginator = Paginator(books, 18)
    page = request.GET.get('page')
    books = paginator.get_page(page)
    return render(request, 'system/recommend.html',context={'books':books,'page':page})

def get_echart_data(request):
    returnData = {'echart_1':{},'echart_2':{},'echart_3':{},'echart_4':{},'echart_5':{},'echart_6':{}}
    books = Book.objects.all()

    # echart_1
    category_results = books.values('category').annotate(count=Count('id'))
    returnData['echart_1']['x_data'] = [item['category'] for item in list(category_results)]
    returnData['echart_1']['y_data'] = [item['count'] for item in list(category_results)]

    # echart_2
    prices_results = list(books.values_list('now_price', flat=True))
    bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, np.inf]
    bin_names = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90', '90-100', '100+']
    # 将价格分组
    counts, bins = np.histogram(prices_results, bins=bins)
    # 构造返回结果
    returnData['echart_2']['x_data'] = bin_names
    returnData['echart_2']['y_data'] = counts.tolist()

    # echart_3
    detail_results = books.filter(star__gt=90).values('detail')
    content = ""
    for result in detail_results:
        content += result['detail']
    stopwords = set()
    with open('./system/cn_stopword.txt', 'r', encoding='utf-8') as fp:
        for line in fp:
            stopwords.add(line.strip())
    content = jieba.lcut(content, cut_all=False)
    filtered_words = []
    for word in content:
        if word not in stopwords:
            filtered_words.append(word)
    content = filtered_words
    word_counts = Counter(content)  # 对分词做词频统计
    word_counts_top = word_counts.most_common(100)
    returnData['echart_3']['data'] = []
    for key, value in word_counts_top:
        returnData['echart_3']['data'].append({'name': key, 'value': value})

    # echart_4
    publishers = books.values('press').annotate(count=Count('id')).order_by('-count')
    returnData['echart_4']['data'] = [{'name':item['press'],'value':item['count']} for item in publishers[:10]]

    # echart_5
    star_results = books.values('star').annotate(count=Count('id')).order_by('star')
    returnData['echart_5']['x_data'] = [item['star'] for item in list(star_results)]
    returnData['echart_5']['y_data'] = [item['count'] for item in list(star_results)]

    # echart_6
    comment_results = books.values('title','comment_num').order_by('-comment_num')[:5]
    returnData['echart_6']['x_data'] = [item['title'] for item in list(comment_results)]
    returnData['echart_6']['y_data'] = [{'name':item['title'],'value':round(item['comment_num']/10000,2)} for item in list(comment_results)]
    return JsonResponse(returnData,safe=False, json_dumps_params={'ensure_ascii': False})

djangoPreject/templates/system/chart1.html
{% extends "base.html" %}{% load static %}
{% block title %}不同类别下价格区间数量占比{% endblock %}
{% block style %}
    <style>
        a {
            text-decoration: none;
        }

        .category {
            margin-left: 20px;
            font-size: large;
            color: #2a99ff;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="padding-top: 100px; padding-left: 20px">
        <div>
            <a href="{% url 'system:chart1' %}">
                <span class="category">刷新</span>
            </a>
            {% for item in categories %}
                <a href="{% url 'system:chart1' %}?category={{ item.category }}">
                    <span class="category">{{ item.category }}</span>
                </a>
            {% endfor %}
        </div>
        {% if category %}
            <div id="chart" style="height: 800px;padding-top: 100px;"></div>
        {% endif %}
    </div>
{% endblock %}
{% block script %}
    <script>
        var data =
        {{ data|safe }}
        var Chart = echarts.init(document.getElementById('chart'));
        var option = {
            title: {
                text: '价格区间数量统计',
                left: 'left'
            },
            tooltip: {},
            legend: {
                right: 'right'
            },
            xAxis: {
                name: '价格区间',
                type: 'category',
                data: data.x_data
            },
            yAxis: {
                name: '数量',
                type: 'value',
                max: Math.max(...data.y_data) + 20
            },
            series: [{
                name: '数量',
                type: 'bar',
                data: data.y_data,
                itemStyle: {
                    color: new echarts.graphic.LinearGradient(
                        0, 0, 0, 1,
                        [
                            {offset: 0, color: '#83bff6'},
                            {offset: 0.5, color: '#188df0'},
                            {offset: 1, color: '#188df0'}
                        ]
                    )
                },
                markPoint: {
                    symbolSize: 100,
                    label: {
                        show: true,
                        formatter: function (param) {
                            return param.name;
                        }
                    },
                    data: [
                        {name: '最小值', type: 'min'},
                        {name: '最大值', type: 'max'}
                    ]
                }
            }]
        };


        Chart.setOption(option);
    </script>
{% endblock %}

djangoPreject/templates/system/chart2.html
{% extends "base.html" %}{% load static %}
{% block title %}不同类别下出版社发行量Top5{% endblock %}
{% block style %}
    <style>
        a {
            text-decoration: none;
        }

        .category {
            margin-left: 20px;
            font-size: large;
            color: #ff512a;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="padding-top: 100px; padding-left: 20px">
        <div>
            <a href="{% url 'system:chart2' %}">
                <span class="category">刷新</span>
            </a>
            {% for item in categories %}
                <a href="{% url 'system:chart2' %}?category={{ item.category }}">
                    <span class="category">{{ item.category }}</span>
                </a>
            {% endfor %}
        </div>
        {% if category %}
            <div id="chart" style="height: 800px;padding-top: 100px;"></div>
        {% endif %}
    </div>
{% endblock %}
{% block script %}
    <script>
        var data =
        {{ data|safe }}
        var Chart = echarts.init(document.getElementById('chart'));
        option = {
    title: {
        text: '',
        subtext: '',
        left: 'center'
    },
    tooltip: {
        trigger: 'item',
        formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    legend: {
        orient: 'vertical',
        left: 'right',
        data: data.x_data
    },
    series: [
        {
            name: '出版社',
            type: 'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: false,
            label: {
                show: false,
                position: 'center'
            },
            emphasis: {
                label: {
                    show: true,
                    fontSize: '30',
                    fontWeight: 'bold'
                }
            },
            labelLine: {
                show: false
            },
            data: data.y_data,
            itemStyle: {
                normal: {
                    color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                            offset: 0,
                            color: '#ffa1df'
                        },
                        {
                            offset: 1,
                            color: '#ff00cc'
                        }
                    ]),
                    shadowBlur: 200,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};
        Chart.setOption(option);
    </script>
{% endblock %}

djangoPreject/templates/system/chart_pie.html
{% extends "base.html" %}{% load static %}
{% block title %}评论情感倾向饼图{% endblock %}
{% block style %}

{% endblock %}
{% block content %}
<body>
    <div>{{ pie_html|safe }}</div>
</body>
{% endblock %}
{% block script %}

{% endblock %}

djangoPreject/templates/system/comment_list.html
{% extends "base.html" %}{% load static %}
{% block title %}评论数据展示{% endblock %}
{% block style %}

{% endblock %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>评论数据</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>评论数据</h1>
    <table>
        <thead>
            <tr>
                <th>UID</th>
                <th>昵称</th>
                <th>评论内容</th>
                <th>日期</th>
                <th>评论情感极性</th>
                <th>评论情感概率</th>
            </tr>
        </thead>
        <tbody>
            {% for item in comments %}
            <tr>
                <td>{{ item.uid }}</td>
                <td>{{ item.nickname }}</td>
                <td>{{ item.content }}</td>
                <td>{{ item.date }}</td>
                <td>{{ item.polarity }}</td>
                <td>{{ item.probability }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}
{% block script %}

{% endblock %}

djangoPreject/templates/system/index.html
{% extends "base.html" %}{% load static %}
{% block title %}首页{% endblock %}
{% block style %}
    <style>
        .index {
            padding-top: 250px;
            display: flex;
            justify-content: center;
        }

        .index a {
            margin: auto;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="index">
        <a href="{% url 'system:chart1' %}">
            <button type="button" class="btn btn-primary">&nbsp;&nbsp;&nbsp;不同类别下价格区间数量占比&nbsp;&nbsp;&nbsp;</button>
        </a>
        <a href="{% url 'system:chart2' %}">
            <button type="button" class="btn btn-success">&nbsp;&nbsp;&nbsp;不同类别下出版社发行量Top5&nbsp;&nbsp;&nbsp;</button>
        </a>
        <a href="{% url 'system:recommend' %}">
            <button type="button" class="btn btn-info">&nbsp;&nbsp;&nbsp;图书推荐&nbsp;&nbsp;&nbsp;</button>
        </a>
        <a href="{% url 'system:show' %}">
            <button type="button" class="btn btn-warning">&nbsp;&nbsp;&nbsp;大屏展示&nbsp;&nbsp;&nbsp;</button>
        </a>

        <a href="{% url 'system:pie_chart' %}">
            <button type="button" class="btn btn-warning">&nbsp;&nbsp;&nbsp;评论情感倾向饼图&nbsp;&nbsp;&nbsp;</button>
        </a>
        <a href="{% url 'system:average_sentiment' %}">
            <button type="button" class="btn btn-warning">&nbsp;&nbsp;&nbsp;评论情感概率平均值折线图&nbsp;&nbsp;&nbsp;</button>
        </a>
        <a href="{% url 'system:comment_list' %}">
            <button type="button" class="btn btn-warning">&nbsp;&nbsp;&nbsp;评论数据展示&nbsp;&nbsp;&nbsp;</button>
        </a>

    </div>
{% endblock %}

djangoPreject/templates/system/recommend.html
{% extends "base.html" %}{% load static %}
{% block title %}图书推荐{% endblock %}
{% block style %}

{% endblock %}
{% block content %}
<div class="container" style="padding-top: 100px">
    <div class="row">
        {% for book in books %}
        <div class="col-md-4">
            <a href="{{ book.book_url }}" target="_blank" style="text-decoration: none;">
                <div class="card mb-4 shadow-sm" style="border: none;">
                    <img class="card-img-top" src="{{ book.img_url }}" alt="{{ book.title }}" style="height: 300px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 20px; font-weight: bold; margin-bottom: 10px;">{{ book.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted" style="font-size: 16px; margin-bottom: 10px;">{{ book.press }}</h6>
                        <p class="card-text" style="font-size: 18px; font-weight: bold; margin-bottom: 5px; color: #FF5722;">价格：{{ book.now_price }}元</p>
                        <p class="card-text" style="font-size: 16px; margin-bottom: 5px;">评分：{{ book.star }}（{{ book.comment_num }}条评论）</p>
                        <p class="card-text" style="font-size: 16px; margin-bottom: 20px;">发布时间：{{ book.createTime }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


    <div class="paginator row">
        <div class="m-auto">
        <span class="step-links">
            {% if books.has_previous %}
                <a href="?page=1"
                   class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ books.previous_page_number }}"
                   class="btn btn-secondary">
                    {{ books.previous_page_number }}
                </a>
            {% endif %}
            <span class="current btn btn-danger btn-lg">
                {{ books.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if books.has_next %}
                <a href="?page={{ books.next_page_number }}"
                   class="btn btn-secondary">
                    {{ books.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ books.paginator.num_pages }}"
                   class="btn btn-success"
                >
                    {{ books.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
        </div>
    </div>
{% endblock %}

djangoPreject/templates/system/sentiment_avg_line_chart.html
{% extends "base.html" %}{% load static %}
{% block title %}评论情感概率平均值折线图{% endblock %}
{% block style %}

{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Daily Sentiment Average</title>
    <script src="https://code.highcharts.com/highcharts.js"></script>
</head>
<body>
    <div id="container" style="min-width: 400px; height: 400px; margin: 0 auto"></div>

    <script>
        var data = JSON.parse('{{ data|safe }}');

        Highcharts.chart('container', {
            title: {
                text: 'Daily Sentiment Average'
            },
            xAxis: {
                categories: data.dates
            },
            yAxis: {
                title: {
                    text: 'Sentiment Average'
                }
            },
            series: [{
                name: 'Sentiment Average',
                data: data.sentiments
            }]
        });
    </script>
</body>
</html>

{% endblock %}
{% block script %}

{% endblock %}

djangoPreject/templates/system/show.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>岗位可视化分析报告</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/comon0.css' %}">
{#    <script type="text/javascript" src="{% static '/js/echarts.min.js' %}"></script>#}
    <script type="text/javascript" src="{% static '/js/main.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/china.js' %}"></script>
        <script src="https://www.jq22.com/jquery/echarts-4.2.1.min.js"></script>
    <script type="text/javascript" src="{% static '/js/echarts-wordcloud.min.js' %}"></script>
</head>
<script>
    $(window).load(function () {
        $(".loading").fadeOut()
    });

    $(document).ready(function () {
        var whei = $(window).width();
        $("html").css({fontSize: whei / 20});
        $(window).resize(function () {
            var whei = $(window).width();
            $("html").css({fontSize: whei / 20})
        });
    });
</script>
<body>
<div class="canvas" style="opacity: .2">
    <iframe frameborder="0" src="{% static '/js/index.html' %}" style="width: 100%; height: 100%"></iframe>
</div>
<div class="loading">
    <div class="loadbox"><img src="{% static '/picture/loading.gif' %}"> 页面加载中...</div>
</div>
<div class="head">
    <h1>舆情分析大屏展示系统</h1>
    <a href="{% url 'system:index' %}" style="margin-left: 10px;font-size: large">返回</a>
    <div class="weather"><span id="showTime"></span></div>
    <script>
        var t = null;
        t = setTimeout(time, 1000);//開始运行
        function time() {
            clearTimeout(t);//清除定时器
            dt = new Date();
            var y = dt.getFullYear();
            var mt = dt.getMonth() + 1;
            var day = dt.getDate();
            var h = dt.getHours();//获取时
            var m = dt.getMinutes();//获取分
            var s = dt.getSeconds();//获取秒
            document.getElementById("showTime").innerHTML = y + "年" + mt + "月" + day +"日"+ "-" + h + "时" + m + "分" + s + "秒";
            t = setTimeout(time, 1000); //设定定时器，循环运行
        }
    </script>

</div>
<div class="mainbox">
    <ul class="clearfix">
        <li>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">各类别发行数量</div>
                <div class="allnav" id="echart1"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">价格分布情况</div>
                <div class="allnav" id="echart2"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">详情内容词云图</div>
                <div class="allnav" id="echart3"></div>
                <div class="boxfoot"></div>
            </div>
        </li>
        <li>
            <div class="bar">
                <div class="barbox">
                    <ul class="clearfix">
                        <li class="pulll_left counter">{{ count_sum }}</li>
                        <li class="pulll_left counter">{{ count_today }}</li>
                    </ul>
                </div>
                <div class="barbox2">
                    <ul class="clearfix">
                        <li class="pulll_left">总数据量</li>
                        <li class="pulll_left">今日抓取量</li>
                    </ul>
                </div>
            </div>
            <div class="map">
                <div class="map1"><img src="{% static '/picture/lbx.png' %}"></div>
                <div class="map2"><img src="{% static '/picture/jt.png' %}"></div>
                <div class="map4" id="map_1"></div>
            </div>
        </li>
        <li>
            <div class="boxall" style="height:3.4rem">
                    <div class="alltitle">出版社发行数量Top10</div>
                    <div class="allnav" id="echart4"></div>
                    <div class="boxfoot"></div>
                <div style="height:100%; width: 100%;">
                </div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">舆情评分占比情况</div>
                <div class="allnav" id="echart5"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3rem">
                <div class="alltitle"></div>
                <div class="allnav" id="echart6"></div>
                <div class="boxfoot"></div>
            </div>
        </li>
    </ul>
</div>
<div class="back"></div>
</body>
</html>

djangoPreject/templates/system/word_cloud.html
{% extends "base.html" %}{% load static %}
{% block title %}评论情感倾向饼图{% endblock %}
{% block style %}

{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>词云图页面</title>
    <!-- 引入 Pyecharts 所需的 CDN 地址 -->
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.2.2/dist/echarts.min.js"></script>
</head>
<body>
    <!-- 在页面中显示词云图 -->
    {{ word_cloud_html|safe }}
</body>
</html>

{% endblock %}
{% block script %}

{% endblock %}