djangoPreject/djangoPreject/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('system/', include(('system.urls', 'system'), namespace='system')),
]

djangoPreject/system/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('word_cloud/', views.word_cloud, name='word_cloud'),
    path('average_sentiment/', views.average_sentiment, name='average_sentiment'),
    path('pie_chart/', views.pie_chart, name='pie_chart'),
    path('comment_list/', views.comment_list, name='comment_list'),
    path('index/', views.index, name='index'),
    path('show/', views.show, name='show'),
    path('chart1/', views.chart1, name='chart1'),
    path('chart2/', views.chart2, name='chart2'),
    path('recommend/', views.recommend, name='recommend'),
    path('get_echart_data/', views.get_echart_data, name='get_echart_data')
]

djangoPreject/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.Register, name='register'),
    path('delete/<int:id>', views.Delete, name='delete'),
]

djangoPreject/templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

djangoPreject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="{% static 'layer/src/layer.js' %}"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.4.2/echarts.min.js"></script>
</head>
<body>
{% block style %}{% endblock style %}
{% include 'header.html' %}
<div id="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
{% include 'footer.html' %}
{% block script %}{% endblock script %}
{% include 'back_to_top_func.html' %}
<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    #wrapper {
        min-height: 100%;
        margin-bottom: -60px;
        background-color: #faf9f9;
    }

    #push {
        height: 60px;
    }
</style>
</body>
</html>

djangoPreject/templates/footer.html
{% load static %}
<div>
    <br>
</div>
<footer class="py-3 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 舆情分析大屏展示系统 2023</p>
    </div>
</footer>

djangoPreject/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">舆情分析大屏展示系统</a>
        <a class="nav-link" id="showTime" style="color: white">
        </a>
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'system:index' %}">首页</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a>
                        </div>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'system:show' %}" target="_blank">大屏展示</a>
                    </li>
                    <li>
                        <a class="nav-link" href="http://127.0.0.1:8000/admin" target="_blank">后台管理</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}">登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% if user.is_authenticated %}
    <form
            style="display: none;"
            id="user_delete"
            action="{% url 'user:delete' user.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                }
            })
        }
    </script>
    <script>
        var t = null;
        t = setTimeout(time, 1000);//開始运行
        function time() {
            clearTimeout(t);//清除定时器
            dt = new Date();
            var y = dt.getFullYear();
            var mt = dt.getMonth() + 1;
            var day = dt.getDate();
            var h = dt.getHours();//获取时
            var m = dt.getMinutes();//获取分
            var s = dt.getSeconds();//获取秒
            document.getElementById("showTime").innerHTML = y + "年" + mt + "月" + day + "日" + "-" + h + "时" + m + "分" + s + "秒";
            t = setTimeout(time, 1000); //设定定时器，循环运行
        }
    </script>
{% endif %}